import { adminTest as test, expect } from "./fixtures/roles";
import { getApiBaseUrl } from "./fixtures/env";

test("admin can navigate analytics to student detail via users list @smoke", async ({ page }) => {
    // Admin auth comes from storage state generated by Playwright setup project.
    await page.goto("/admin");

    // Sidebar is present in admin layout.
    await expect(page.getByRole("button", { name: "Analytics" })).toBeVisible({ timeout: 30_000 });
    await expect(page.getByRole("button", { name: "Users" })).toBeVisible({ timeout: 30_000 });

    const apiBaseUrl = getApiBaseUrl().replace(/\/+$/, "");
    await page.route(`${apiBaseUrl}/admin/leaderboard`, async (route) => {
        await route.fulfill({
            status: 200,
            contentType: "application/json",
            body: JSON.stringify({
                data: [
                    { username: "student_one", xpTotal: 420, attemptCount: 12, averageScore: 88.5 },
                    { username: "student_two", xpTotal: 310, attemptCount: 9, averageScore: 81.2 },
                ],
            }),
        });
    });

    // Navigate to analytics and verify KPI cards + leaderboard table render.
    await page.goto("/admin/analytics");
    await expect(page).toHaveURL(/\/admin\/analytics(?:\/)?$/);

    await expect(page.getByText("Total Users")).toBeVisible({ timeout: 30_000 });
    await expect(page.getByText("Total Quizzes")).toBeVisible({ timeout: 30_000 });
    await expect(page.getByText("Quiz Attempts")).toBeVisible({ timeout: 30_000 });
    await expect(page.getByText("Average Pass Rate")).toBeVisible({ timeout: 30_000 });

    await expect(page.getByRole("heading", { name: "Top 10 Users by XP" })).toBeVisible({ timeout: 30_000 });

    const leaderboardTable = page.locator("table").filter({
        has: page.getByRole("columnheader", { name: "Rank" }),
    }).first();
    await expect(leaderboardTable).toBeVisible({ timeout: 30_000 });

    // Navigate to users list and ensure rows render.
    await page.goto("/admin/users");
    await expect(page).toHaveURL(/\/admin\/users(?:\/)?$/);
    await expect(page.getByRole("heading", { name: "User Management" })).toBeVisible({ timeout: 30_000 });

    const userRows = page.locator("tbody tr");
    await expect(userRows.first()).toBeVisible({ timeout: 30_000 });

    // Prefer a non-admin (User role) row when available.
    const rowCount = await userRows.count();
    let targetRow = userRows.first();

    for (let i = 0; i < rowCount; i++) {
        const row = userRows.nth(i);
        const roleSelect = row.locator("select");
        if (await roleSelect.count()) {
            const roleValue = (await roleSelect.first().inputValue()).trim().toLowerCase();
            if (roleValue === "user") {
                targetRow = row;
                break;
            }
        }
    }

    const idText = (await targetRow.locator("td").first().innerText()).trim();
    const clickedId = Number.parseInt(idText, 10);

    await targetRow.click();

    if (Number.isFinite(clickedId)) {
        await expect(page).toHaveURL(new RegExp(`/admin/students/${clickedId}$`), { timeout: 30_000 });
    } else {
        await expect(page).toHaveURL(/\/admin\/students\/\d+$/, { timeout: 30_000 });
    }

    // Student detail page markers.
    await expect(page.getByRole("button", { name: "Back to Users" })).toBeVisible({ timeout: 30_000 });
    await expect(page.getByRole("heading", { name: "Quiz Attempt History" })).toBeVisible({ timeout: 30_000 });
});
